- hosts: stratum1
  roles:
  - eessi.stratum1

  vars:
    # The license key for the Geo API:
    # https://cvmfs.readthedocs.io/en/stable/cpt-replica.html#geo-api-setup
    # For some unclear reason, the Stratum 1 installation fails when this is not set:
    # https://github.com/EESSI/filesystem-layer/issues/2
    cvmfs_geo_license_key: INSERT_YOUR_KEY

    # Everything after this is optional. The defaults should provide a working stratum1
    # with local monitoring enabled.

    # Set the node as a public node. If the node is set as public the prometheus
    # instance will allow monitoring.eessi-infra.org to connect to scrape data.
    eessi_public: false

    # Enable monitoring on nodes, defaults to true.
    # This will install grafana, prometheus, node_exporter, and cvmfs_exporter
    # on the monitored node.
    eessi_monitoring: false

    # All services bind to localhost, unless eessi_public is set to
    # true, in that case grafana and prometheus binds to "*". 
    eessi_service_ports:
      grafana: 3000
      prometheus: 9090
      node_exporter: 9100
      cvmfs_exporter: 9101

    # If you want to use your own Squid configuration template for the Stratum 1
    # local_stratum1_cvmfs_squid_conf_src: "/path/to/your/template"